In [ ]:
# Initialize the matrix

import numpy as np

A = np.array([[2, 3, 1],
              [4, 2, 1],
              [2, 3, 1]])

print(A)

[[2 3 1]
 [4 2 1]
 [2 3 1]]


In [ ]:




A = np.array([[2, 3, 1],
              [4, 2, 1],
              [2, 3, 1]])
B = np.array([[2, 3, 1],
              [1, 2, 1],
              [2, 3, 1]])

print(A + B)

[[4 6 2]
 [5 4 2]
 [4 6 2]]


In [ ]:
# matrix multiplication

A = np.array([[2, 3, 1],
              [4, 2, 1],
              [2, 3, 1]])
B = np.array([[2, 3, 1],
              [1, 2, 1],
              [2, 3, 1]])

print(A.dot(B)) # A@B HIGHER VERSION OF PYTHON 

[[ 9 15  6]
 [12 19  7]
 [ 9 15  6]]


In [3]:
# Matrix Inversion # linear algebra in numpy for inverse 

import numpy as np

A = np.array([[2, 4, 1],
              [5, 2, 7],
              [9, 4, 3]])

print( np.linalg.inv(A) )  # it will get an error for singular matrix


[[-0.14666667 -0.05333333  0.17333333]
 [ 0.32       -0.02       -0.06      ]
 [ 0.01333333  0.18666667 -0.10666667]]


In [4]:
# Element wise multiplication

A = np.array([[2, 3, 1],
              [4, 2, 1],
              [2, 3, 1]])

B = np.array([[2, 3, 1],
              [1, 2, 1],
              [2, 3, 1]])

print( A * B)

[[4 9 1]
 [4 4 1]
 [4 9 1]]


In [6]:
# Eigen values 

A = np.array([[2, 3, 1],
              [4, 2, 1],
              [2, 3, 1]])

print( np.linalg.eigvals(A) )

[ 6.40512484e+00 -1.40512484e+00  8.55045880e-17]
